### ISSUE TITLE
ERROR Error: listen EADDRINUSE

### ISSUE THREAD

**Issue by tholu** [sdelements/hubot-lets-chat#17]
In a local installation of version 0.0.7, I get the following error when starthing hubot:

```
[Thu Jul 09 2015 15:03:45 GMT+0200 (CEST)] ERROR Error: listen EADDRINUSE
  at exports._errnoException (util.js:746:11)
  at Server._listen2 (net.js:1156:14)
  at listen (net.js:1182:10)
  at net.js:1280:9
  at dns.js:85:18
  at process._tickCallback (node.js:355:11)
```

**Comment by tholu** [comment]
```export PORT=5001``` did the trick.
