### ISSUE TITLE
Deploying hubot to heroku

### ISSUE THREAD

**Issue by depinav** [sdelements/hubot-lets-chat#8]
Hey all ran into another issue with the lets-chat adapter. I've deployed my bot to heroku and set the `heroku config:add` for the env variables. When I run it the bot never appears. I checked the heroku logs and I get this
```
2015-02-20T13:33:14.152945+00:00 app[web.1]: Fri, 20 Feb 2015 13:33:14 GMT connect deprecated limit: Restrict request size at location of read at node_modules/hubot/node_modules/express/node_modules/connect/lib/middleware/multipart.js:86:15
2015-02-20T13:33:14.210741+00:00 app[web.1]: [Fri Feb 20 2015 13:33:14 GMT+0000 (UTC)] ERROR Cannot load adapter lets-chat - TypeError: Cannot call method 'split' of undefined
2015-02-20T13:33:14.152140+00:00 app[web.1]: Fri, 20 Feb 2015 13:33:14 GMT connect deprecated multipart: use parser (multiparty, busboy, formidable) npm module instead at node_modules/hubot/node_modules/express/node_modules/connect/lib/middleware/bodyParser.js:56:20
2015-02-20T13:33:15.112134+00:00 heroku[web.1]: Process exited with status 1
2015-02-20T13:33:15.122294+00:00 heroku[web.1]: State changed from starting to crashed
2015-02-20T13:33:15.123010+00:00 heroku[web.1]: State changed from crashed to starting
2015-02-20T13:33:16.672237+00:00 heroku[web.1]: Starting process with command `bin/hubot -a lets-chat -n pinebot`
2015-02-20T13:33:18.218139+00:00 app[web.1]: Detected 512 MB available memory, 512 MB limit per process (WEB_MEMORY)
2015-02-20T13:33:18.218155+00:00 app[web.1]: Recommending WEB_CONCURRENCY=1
```

Any guidance or suggestions?

**Comment by hhaidar** [comment]
did you specify the rooms env variable?

**Comment by depinav** [comment]
I think so... I used 
``` sh
heroku config:add HUBOT_LCB_TOKEN= <user auth token>
heroku config:add HUBOT_LCB_ROOM=<room id>
```

**Comment by hhaidar** [comment]
Should be HUBOT_LCB_ROOMS, missing an S.

**Comment by hhaidar** [comment]
also you might need to specify HOST, PROTOCOL and PORT if its not hosted on http://localhost:5000

**Comment by depinav** [comment]
so for the host I set it to the deployed chats url "name.herokuapp.com" and for the port I set it to "process.env.PORT". Im wondering, does this set it to it's own port as opposed to the chat's port?

**Comment by hhaidar** [comment]
It should be the chat severs port.

hubot has other settings for an http listener, but that's beyond this for now :)

**Comment by depinav** [comment]
How do I find out what port the chat is running on? I can't find that info anywhere.

**Comment by hhaidar** [comment]
Port 80 for Heroku!

**Comment by depinav** [comment]
Should the HOSTNAME be the same as the chat apps url?

**Comment by depinav** [comment]
Scratch that. Got it working. Closing this now. Thanks @hhaidar

**Comment by hhaidar** [comment]
Ah cool, good man @depinav :D
